"""
In-memory analysis snapshot cache.

Design intent:
- Each run_id maps to ONE authoritative analysis snapshot.
- Snapshot is generated by analysis_engine.run_full_analysis().
- Snapshot may be overwritten for the SAME run_id (intentional).
- Used to prevent stale dashboards and cross-run contamination.

Eviction:
- Maximum _STORE_MAX_SIZE snapshots kept in memory.
- Oldest entry (FIFO) evicted when capacity is reached.
- Prevents unbounded memory growth on servers that process many uploads.

Scope:
- Single-process / lab / SOC simulation use.
- NOT thread-safe or multi-worker safe by design.
- In production, replace with Redis / task-result store.
"""

import threading
from typing import Any, Dict, List, Optional, Tuple

# -------------------------------------------------------------------
# Internal store
# -------------------------------------------------------------------

_ANALYSIS_STORE: Dict[str, dict] = {}   # { run_id: analysis_context }
_STORE_ORDER:    List[str]        = []   # insertion-order list for FIFO eviction
_STORE_LOCK      = threading.Lock()      # protects both store and order list
_STORE_MAX_SIZE  = 100                   # max snapshots in memory before eviction (Phase 9)
_SNAPSHOT_VERSIONS: Dict[str, int] = {}  # { run_id: current_version_counter }

_READ_SAFE_MUTABLE_FIELDS = (
    "timeline",
    "burst_aggregates",
    "detections",
    "correlations",
    "correlations_detail",
    "correlation_campaigns",
    "correlation_hunts",
    "top_dangerous_bursts",
    "baseline_execution_context",
    "events",
    "interesting",
    "recent",
    "normalized_detections",
    "incidents",
    "profiling",
    "meta",
    "attack_narrative",
    "forensic_metadata",
)

_TERMINAL_SNAPSHOT_STATUSES = frozenset({"failed", "error", "complete", "degraded", "cancelled"})

_AUTHORITATIVE_STAGE_ORDER = {
    "initialization": 1,
    "load_events": 2,
    "burst_assembly": 10,
    "correlation_scoring": 20,
    "persistence": 30,
    "snapshot_inputs": 40,
    "snapshot_assembly": 50,
    "serialization": 60,
    "dashboard_serialization": 60,
    "failure_snapshot_generation": 70,
    "finalization_snapshot": 80,
    "finalization_state": 90,
    "completion_publication": 100,
    "complete": 110,
    "failed": 110,
    "error": 110,
}

_SNAPSHOT_TELEMETRY_FIELDS = (
    "events",
    "timeline",
    "burst_aggregates",
    "detections",
    "correlations",
    "correlations_detail",
    "correlation_campaigns",
    "correlation_hunts",
    "top_dangerous_bursts",
    "baseline_execution_context",
    "interesting",
    "recent",
    "normalized_detections",
    "incidents",
    "events_per_hour",
    "events_by_severity",
    "attack_narrative",
    "forensic_metadata",
    "meta",
)

import logging
import time
log = logging.getLogger("analysis_cache")


def _current_process_rss_bytes() -> int:
    try:
        import psutil

        return int(psutil.Process().memory_info().rss)
    except Exception:
        return 0

# -------------------------------------------------------------------
# Hybrid Versioning & Status Guards (The 10/10 Certification Phase)
# -------------------------------------------------------------------
# Atomic stage priorities for monotonic progress
STAGE_ORDER = {"primary": 1, "insight": 2, "fused": 3}


def _stage_priority(stage: Optional[str]) -> int:
    if not stage:
        return 0
    return _AUTHORITATIVE_STAGE_ORDER.get(str(stage).strip().lower(), 0)

# ---------------------------------------------------
# Snapshot API
# ---------------------------------------------------

def _normalize_snapshot(
    snapshot: dict,
    *,
    timeline_offset: int = 0,
    timeline_limit: Optional[int] = None,
    copy_mutable_fields: bool = True,
) -> dict:
    """Production-grade schema enforcement on read. Prevents mutation of shared cache."""
    if not isinstance(snapshot, dict):
        return None

    # Lock memory while avoiding a full deep-copy on every dashboard read.
    snap = dict(snapshot)
    if copy_mutable_fields:
        for key in _READ_SAFE_MUTABLE_FIELDS:
            value = snap.get(key)
            if key == "timeline" and isinstance(value, list):
                start = max(int(timeline_offset or 0), 0)
                end = None if timeline_limit is None else start + max(int(timeline_limit or 0), 0)
                snap[key] = list(value[start:end])
            elif isinstance(value, list):
                snap[key] = list(value)
            elif isinstance(value, dict):
                snap[key] = dict(value)
    else:
        value = snap.get("timeline")
        if isinstance(value, list):
            start = max(int(timeline_offset or 0), 0)
            end = None if timeline_limit is None else start + max(int(timeline_limit or 0), 0)
            snap["timeline"] = value[start:end]

    # 🔒 Strict Schema Enforcement
    snap["timeline"] = snap.get("timeline") or []
    snap["burst_aggregates"] = snap.get("burst_aggregates") or []

    # 🔒 Status Normalization — ensure UI always has a definitive state
    raw_status = str(snap.get("status", "") or "").strip().lower()
    if raw_status in ("running", "processing", "in_progress", "in-progress"):
        snap["status"] = "processing"
    elif raw_status in ("error", "failed"):
        snap["status"] = "failed"
    elif raw_status in ("complete", "completed", "done"):
        snap["status"] = "complete"
    elif raw_status == "degraded":
        snap["status"] = "degraded"
    elif raw_status:
        snap["status"] = raw_status
    else:
        snap["status"] = "complete"  # Default to complete for legacy snapshots

    # 🔒 Timeline Guard — log error if timeline is missing structure
    if "timeline" not in snapshot:
        log.error("[CACHE] Invalid snapshot schema: 'timeline' key missing for run_id lookup")

    narrative = snap.get("attack_narrative") or {}
    snap["attack_narrative"] = {
        "summary": narrative.get("summary", "No threats detected"),
        "stage": narrative.get("stage", "None"),
        "score": float(narrative.get("score", 0)),
        "is_attack": bool(narrative.get("is_attack", False))
    }

    meta = snap.get("meta")
    if isinstance(meta, dict):
        snap["meta"] = dict(meta)

    return snap


def _collect_snapshot_telemetry(snapshot: dict) -> dict:
    telemetry = {
        "top_level_keys": len(snapshot) if isinstance(snapshot, dict) else 0,
        "dict_nodes": 0,
        "list_nodes": 0,
        "leaf_nodes": 0,
        "max_depth": 0,
        "reused_refs": 0,
        "field_sizes": {},
        "field_depths": {},
        "field_types": {},
    }

    seen_ids = set()

    def _walk(value: Any, depth: int) -> None:
        if isinstance(value, dict):
            value_id = id(value)
            if value_id in seen_ids:
                telemetry["reused_refs"] += 1
                return
            seen_ids.add(value_id)
            telemetry["dict_nodes"] += 1
            telemetry["max_depth"] = max(telemetry["max_depth"], depth)
            for nested in value.values():
                _walk(nested, depth + 1)
            return

        if isinstance(value, (list, tuple)):
            value_id = id(value)
            if value_id in seen_ids:
                telemetry["reused_refs"] += 1
                return
            seen_ids.add(value_id)
            telemetry["list_nodes"] += 1
            telemetry["max_depth"] = max(telemetry["max_depth"], depth)
            for nested in value:
                _walk(nested, depth + 1)
            return

        telemetry["leaf_nodes"] += 1
        telemetry["max_depth"] = max(telemetry["max_depth"], depth)

    for field in _SNAPSHOT_TELEMETRY_FIELDS:
        value = snapshot.get(field) if isinstance(snapshot, dict) else None
        telemetry["field_types"][field] = type(value).__name__ if value is not None else "missing"
        if isinstance(value, dict):
            telemetry["field_sizes"][field] = len(value)
            telemetry["field_depths"][field] = 1
            _walk(value, 1)
        elif isinstance(value, (list, tuple)):
            telemetry["field_sizes"][field] = len(value)
            telemetry["field_depths"][field] = 1 if not value else 2
            if field == "events" and len(value) > 5000:
                telemetry["field_depths"][field] = 2
                telemetry["field_types"][field] = f"{type(value).__name__}[guarded]"
                continue
            _walk(value, 1)
        elif value is None:
            telemetry["field_sizes"][field] = 0
            telemetry["field_depths"][field] = 0
        else:
            telemetry["field_sizes"][field] = 1
            telemetry["field_depths"][field] = 1

    return telemetry


def _copy_snapshot_for_store(snapshot: dict) -> dict:
    stored = {key: value for key, value in snapshot.items() if key != "events"}

    for key, value in list(stored.items()):
        if isinstance(value, dict):
            stored[key] = dict(value)
        elif isinstance(value, list):
            stored[key] = list(value)

    meta = stored.get("meta")
    if isinstance(meta, dict):
        meta_copy = dict(meta)
        profiling_inputs = meta_copy.get("profiling_inputs")
        if isinstance(profiling_inputs, dict):
            meta_copy["profiling_inputs"] = dict(profiling_inputs)
        stored["meta"] = meta_copy

    narrative = stored.get("attack_narrative")
    if isinstance(narrative, dict):
        stored["attack_narrative"] = dict(narrative)

    forensic_metadata = stored.get("forensic_metadata")
    if isinstance(forensic_metadata, dict):
        stored["forensic_metadata"] = dict(forensic_metadata)
    return stored


def publish_analysis_stage_progress(
    run_id: str,
    *,
    state: str,
    progress: int,
    message: str,
    active_stage: Optional[str] = None,
    operation_label: Optional[str] = None,
    stage_started_at: Optional[float] = None,
    processed_events: int = 0,
    total_events: int = 0,
    metrics: Optional[Dict[str, Any]] = None,
    error: Optional[str] = None,
    traceback_summary: Optional[str] = None,
    heartbeat_reset: bool = True,
) -> None:
    if not run_id:
        return

    now = time.time()
    stage_elapsed_seconds = 0.0
    if stage_started_at is not None:
        try:
            stage_elapsed_seconds = round(time.monotonic() - float(stage_started_at), 3)
        except Exception:
            stage_elapsed_seconds = 0.0

    with _STORE_LOCK:
        snapshot = _ANALYSIS_STORE.get(run_id)
        if snapshot is None:
            snapshot = {"timeline": [], "burst_aggregates": [], "status": state}
            _ANALYSIS_STORE[run_id] = snapshot
            if run_id not in _STORE_ORDER:
                _STORE_ORDER.append(run_id)

        meta = snapshot.get("meta")
        if not isinstance(meta, dict):
            meta = {}
            snapshot["meta"] = meta

        existing_stage = str(snapshot.get("active_stage") or snapshot.get("pipeline_stage") or meta.get("pipeline_stage") or "")
        incoming_stage = str(active_stage or meta.get("pipeline_stage") or "")
        allow_regression = state in ("failed", "error", "complete")
        if not allow_regression and _stage_priority(incoming_stage) < _stage_priority(existing_stage):
            return

        current_ver = _SNAPSHOT_VERSIONS.get(run_id, 0) + 1
        _SNAPSHOT_VERSIONS[run_id] = current_ver

        snapshot["status"] = state
        snapshot["progress"] = progress
        snapshot["message"] = message
        snapshot["active_stage"] = active_stage or ""
        snapshot["operation_label"] = operation_label or ""
        snapshot["stage_elapsed_seconds"] = stage_elapsed_seconds
        snapshot["processed_events"] = processed_events
        snapshot["total_events"] = total_events
        snapshot["updated_at"] = now
        snapshot["last_progress_timestamp"] = now
        snapshot["heartbeat_reset_at"] = now if heartbeat_reset else snapshot.get("heartbeat_reset_at", now)
        snapshot["version"] = current_ver
        if error is not None:
            snapshot["error"] = error
        if traceback_summary is not None:
            snapshot["traceback_summary"] = traceback_summary
        if metrics is not None:
            snapshot["metrics"] = dict(metrics)

        meta["pipeline_stage"] = active_stage or meta.get("pipeline_stage") or state
        meta["active_stage"] = active_stage or ""
        meta["operation_label"] = operation_label or ""
        meta["status"] = state
        meta["last_progress_timestamp"] = now
        progress_meta = meta.get("progress")
        if not isinstance(progress_meta, dict):
            progress_meta = {}
            meta["progress"] = progress_meta
        progress_meta.update({
            "state": state,
            "progress": progress,
            "message": message,
            "active_stage": active_stage or "",
            "operation_label": operation_label or "",
            "stage_elapsed_seconds": stage_elapsed_seconds,
            "processed_events": processed_events,
            "total_events": total_events,
            "updated_at": now,
            "heartbeat_reset_at": now if heartbeat_reset else progress_meta.get("heartbeat_reset_at", now),
        })
        if metrics is not None:
            progress_meta["metrics"] = dict(metrics)
        if error is not None:
            progress_meta["error"] = error
        if traceback_summary is not None:
            progress_meta["traceback_summary"] = traceback_summary

        if run_id in _STORE_ORDER:
            _STORE_ORDER.remove(run_id)
        _STORE_ORDER.append(run_id)


def _finalize_snapshot_telemetry(run_id: str, version: int, snapshot: dict) -> None:
    """Compute snapshot telemetry out of band so terminal publication is not blocked."""
    try:
        telemetry = _collect_snapshot_telemetry(snapshot)
        telemetry["copy_elapsed_seconds"] = 0.0
        telemetry["stored_key_count"] = len(snapshot) if isinstance(snapshot, dict) else 0
        telemetry["payload_type"] = type(snapshot).__name__
        telemetry["payload_size_hint"] = sum(
            telemetry["field_sizes"].get(field, 0) for field in _SNAPSHOT_TELEMETRY_FIELDS
        )
    except Exception as exc:
        log.warning("[Cache] Snapshot telemetry failed for run_id=%s: %s", run_id[:16], exc)
        return

    try:
        with _STORE_LOCK:
            current = _ANALYSIS_STORE.get(run_id)
            if not current or _SNAPSHOT_VERSIONS.get(run_id, 0) != version:
                return

            meta = current.get("meta")
            if not isinstance(meta, dict):
                meta = {}
                current["meta"] = meta
            profiling_inputs = meta.get("profiling_inputs")
            if not isinstance(profiling_inputs, dict):
                profiling_inputs = {}
                meta["profiling_inputs"] = profiling_inputs
            profiling_inputs["snapshot_write"] = telemetry
    except Exception as exc:
        log.warning("[Cache] Snapshot telemetry publish failed for run_id=%s: %s", run_id[:16], exc)


def get_analysis_snapshot_slice(
    run_id: str,
    *,
    timeline_offset: int = 0,
    timeline_limit: Optional[int] = None,
) -> Optional[dict]:
    """
    Retrieve a mutation-safe snapshot view without cloning the full timeline.

    Use this for dashboard render paths that only need a preview or a page of
    events. The authoritative full snapshot remains available via
    get_analysis_snapshot().
    """
    if not run_id:
        return None
    enter_started = time.perf_counter()
    thread_id = threading.get_ident()
    log.info("[CACHE_FINALIZE] enter snapshot-slice run_id=%s thread_id=%s offset=%s limit=%s", run_id[:16], thread_id, timeline_offset, timeline_limit)
    with _STORE_LOCK:
        snapshot = _ANALYSIS_STORE.get(run_id)
        if snapshot:
            result = _normalize_snapshot(
                snapshot,
                timeline_offset=timeline_offset,
                timeline_limit=timeline_limit,
                copy_mutable_fields=False,
            )
            log.info("[CACHE_FINALIZE] exit snapshot-slice run_id=%s thread_id=%s elapsed_ms=%d", run_id[:16], thread_id, int((time.perf_counter() - enter_started) * 1000))
            return result
        log.info("[CACHE_FINALIZE] exit snapshot-slice run_id=%s thread_id=%s elapsed_ms=%d", run_id[:16], thread_id, int((time.perf_counter() - enter_started) * 1000))
        return None

def set_analysis_snapshot(run_id: str, snapshot: dict, *, authoritative: bool = False) -> None:
    """
    Store analysis snapshot for a specific run_id with hybrid versioning and validation.
    """
    if not run_id or snapshot is None:
        return

    if not isinstance(snapshot, dict):
        log.warning(f"[Cache] Invalid snapshot type for run_id={run_id[:16]}")
        return

    thread_id = threading.get_ident()
    enter_started = time.perf_counter()
    source_key_count = len(snapshot)
    enter_rss = _current_process_rss_bytes()
    log.info(
        "[CACHE_FINALIZE] enter snapshot-write run_id=%s thread_id=%s keys=%d rss_bytes=%d",
        run_id[:16],
        thread_id,
        source_key_count,
        enter_rss,
    )

    # Schema guard: ensure required fields are present before storing
    if "timeline" not in snapshot:
        log.error("[Cache] Snapshot missing 'timeline' key for run_id=%s — storing anyway", run_id[:16])
        snapshot = dict(snapshot)  # Don't mutate caller's dict
        snapshot["timeline"] = []

    # Ensure status is always set
    if "status" not in snapshot:
        snapshot = dict(snapshot)
        snapshot["status"] = "complete"

    # 🔒 Stage Dominance (Provable Consistency)
    incoming_stage = (
        snapshot.get("pipeline_stage")
        or snapshot.get("active_stage")
        or (snapshot.get("meta", {}) if isinstance(snapshot.get("meta"), dict) else {}).get("pipeline_stage")
        or snapshot.get("status", "primary")
    )
    incoming_status = str(snapshot.get("status", "") or "").strip().lower()
    incoming_priority = _stage_priority(incoming_stage)
    
    copy_started = time.perf_counter()

    lock_started = time.perf_counter()
    with _STORE_LOCK:
        lock_wait_ms = int((time.perf_counter() - lock_started) * 1000)
        log.info("[CACHE_FINALIZE] lock-acquired snapshot-write run_id=%s thread_id=%s lock_wait_ms=%d", run_id[:16], thread_id, lock_wait_ms)
        # DB-Backed Cancellation Shield (Inside Lock)
        # Prevents "Ghost Writes" if cancel happened while acquiring lock.
        if not authoritative:
            from dashboard.db import is_run_cancelled_db
            if is_run_cancelled_db(run_id):
                if incoming_status not in _TERMINAL_SNAPSHOT_STATUSES:
                    log.warning(f"[Cache] PROTECTED: Rejected write for CANCELLED run_id={run_id[:16]}")
                    return
                log.info(f"[Cache] CANCELLED state overridden by terminal snapshot for run_id={run_id[:16]} status={incoming_status or 'unknown'}")

        existing = _ANALYSIS_STORE.get(run_id)
        if existing:
            existing_stage = existing.get("pipeline_stage") or existing.get("active_stage") or existing.get("status", "primary")
            existing_priority = _stage_priority(existing_stage)
            if incoming_priority < existing_priority and incoming_status not in ("failed", "error", "complete", "degraded", "cancelled"):
                log.warning(f"[Cache] PROTECTED: Rejected regressive write ({incoming_stage} < {existing_stage}) for run_id={run_id[:16]}")
                return

        # Structural copy keeps the cache isolated without recursively
        # duplicating every event-sized nested object.
        current_ver = _SNAPSHOT_VERSIONS.get(run_id, 0) + 1
        new_snap = _copy_snapshot_for_store(snapshot)
        new_snap["version"] = current_ver
        new_snap["updated_at"] = time.time()
        new_snap["pipeline_stage"] = incoming_stage
        exit_rss = _current_process_rss_bytes()
        stored_key_count = len(new_snap)
        timeline_rows = len(new_snap.get("timeline") or []) if isinstance(new_snap.get("timeline"), list) else 0
        burst_rows = len(new_snap.get("burst_aggregates") or []) if isinstance(new_snap.get("burst_aggregates"), list) else 0
        recent_rows = len(new_snap.get("recent") or []) if isinstance(new_snap.get("recent"), list) else 0

        elapsed = round(time.perf_counter() - copy_started, 6)
        log.info(
            "[Cache] Snapshot write staged run_id=%s source_keys=%d stored_keys=%d timeline_rows=%d burst_rows=%d recent_rows=%d copy_elapsed=%.3fs rss_delta_bytes=%d thread_id=%s",
            run_id[:16],
            source_key_count,
            stored_key_count,
            timeline_rows,
            burst_rows,
            recent_rows,
            elapsed,
            exit_rss - enter_rss,
            thread_id,
        )
        
        # Guard against corruption
        if "timeline" not in new_snap: new_snap["timeline"] = []
        if "burst_aggregates" not in new_snap: new_snap["burst_aggregates"] = []
        
        # Atomic Swap
        _ANALYSIS_STORE[run_id] = new_snap
        _SNAPSHOT_VERSIONS[run_id] = current_ver
        
        if run_id in _STORE_ORDER:
            _STORE_ORDER.remove(run_id)
        _STORE_ORDER.append(run_id)
        log.info(f"[Cache] Snapshot MASTER SWAP: run_id={run_id[:16]}, stage={incoming_stage}, version={current_ver}")

    log.info(
        "[CACHE_FINALIZE] exit snapshot-write run_id=%s thread_id=%s elapsed_ms=%d lock_wait_ms=%d",
        run_id[:16],
        thread_id,
        int((time.perf_counter() - enter_started) * 1000),
        lock_wait_ms,
    )

    threading.Thread(
        target=_finalize_snapshot_telemetry,
        args=(run_id, current_ver, new_snap),
        daemon=True,
        name=f"snapshot-telemetry-{run_id[:8]}",
    ).start()


def get_analysis_snapshot(run_id: str) -> Optional[dict]:
    """
    Retrieve analysis snapshot for a run_id with mutation-safe normalization.
    """
    if not run_id:
        return None
    with _STORE_LOCK:
        snapshot = _ANALYSIS_STORE.get(run_id)
        if snapshot:
            return _normalize_snapshot(snapshot, copy_mutable_fields=True)
        return None


def clear_analysis_snapshot(run_id: Optional[str] = None, *, clear_all: bool = False) -> None:
    """
    Clear cached analysis snapshots.

    Modes:
    - run_id provided → clears only that run's snapshot
    - clear_all=True  → clears ALL snapshots (explicit only)
    """
    with _STORE_LOCK:
        if run_id:
            _ANALYSIS_STORE.pop(run_id, None)
            if run_id in _STORE_ORDER:
                _STORE_ORDER.remove(run_id)
            return

        if clear_all:
            _ANALYSIS_STORE.clear()
            _STORE_ORDER.clear()


# -------------------------------------------------------------------
# Diagnostics / Debug
# -------------------------------------------------------------------

def _debug_cache_state() -> dict:
    """INTERNAL USE ONLY. Returns cache metadata for debugging."""
    with _STORE_LOCK:
        return {
            "total_runs":  len(_ANALYSIS_STORE),
            "max_size":    _STORE_MAX_SIZE,
            "run_ids":     list(_ANALYSIS_STORE.keys()),
            "evict_order": list(_STORE_ORDER),
        }
